### ISSUE TITLE
Consider gathering user real names during signup

### ISSUE THREAD

**Issue by brianhelba** [girder/django-auth-style#42]
Django-Allauth's [default signup Form](https://github.com/pennersr/django-allauth/blob/c50a30acc0e4553297b0ddb697d55a290ed6d038/allauth/account/forms.py#L376) does not include fields for `first_name` or `last_name` (which are part of [Django's default `User` Model](https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.User.first_name)), so these fields are not populated for new users who signup via a password.

When Allauth's `socialaccount` providers are used, these fields do seem to get populated, if the provider returns the information.

It's possible for this project to override the signup Form and Template to gather `first_name` and `last_name`. This would provide more complete and potentially useful information for `User` entries, but it would make signup slightly more burdensome for the end user and increase the code burden of this project.

**Comment by brianhelba** [comment]
I'd welcome any comments from stakeholders (e.g. projects using "Girder 4") on whether fixing this would be valuable.

**Comment by zachmullen** [comment]
If it's easy enough for downstreams to enable this in their projects, I'd prefer to leave it off by default.

**Comment by aashish24** [comment]
It would be helpful for few projects I have where the users may have to search data owned by some others that they know by name. There could be some other use-cases as well

**Comment by banesullivan** [comment]
> I'd prefer to leave it off by default.

+1 for leaving this off by default. 

I currently do not see any value in adding this to the RGD ecosystem of projects. At the end of the day, we just want one user profile per email address and do not need any further details about the user.

Since the fields already exist and this would only require overriding the signup form, I wouldn't mind seeing the first/last name fields in the default form for all projects. I'd just like to make sure those fields are non-required (even label them as "Optional").

**Comment by banesullivan** [comment]
In hindsight, perhaps RGD wouldn't immediately gain value from this but there could be value in collecting this data down the road. For instance, if we implement the ability for users to create Collections of data and add other users to those collections - It would be way easier to find those users by name as opposed to emails.

**Comment by subdavis** [comment]
I don't care about the default, but having this as a capability would be very helpful on Kitware/dive if/when we transition.  Users currently use G3 search to find each-other's workspaces by their collegue's real names.

**Comment by brianhelba** [comment]
This was recently resolved by https://github.com/girder/django-girder-utils/pull/44
